### ISSUE TITLE
trace on initial login with google api

### ISSUE THREAD

**Issue by ghost** [dyerti/lets-chat-google#1] opened 2015-06-17 22:23 UTC
Not sure if this is me being dumb or my setup is wrong.

background: i forked lets-chat to my own repo to do template updates for my site. other than that the code is lets-chat develop branch 0.4.0.  I enabled G+ API and added a new auth keys.  I am running this on a vm on my laptop for now to dev against.

The trace

TypeError: undefined is not a function
    at Strategy.strategy.redirect (/home/test/velochat-develop/node_modules/passport/lib/middleware/authenticate.js:303:13)
    at Strategy.OAuth2Strategy.authenticate (/home/test/velochat-develop/node_modules/lets-chat-google/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:227:10)
    at attempt (/home/test/velochat-develop/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/home/test/velochat-develop/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Google.authenticate (/home/test/velochat-develop/node_modules/lets-chat-google/lib/auth.js:31:40)
    at /home/test/velochat-develop/app/auth/index.js:209:26
    at fn (/home/test/velochat-develop/node_modules/async/lib/async.js:716:34)
    at /home/test/velochat-develop/node_modules/async/lib/async.js:1169:16
    at /home/test/velochat-develop/node_modules/async/lib/async.js:661:43
    at Object.async.waterfall (/home/test/velochat-develop/node_modules/async/lib/async.js:665:44)

looks like the redirect to google is not working on line 303:
[from node_modules/passport/lib/middleware/authenticate.js ]

```
  strategy.redirect = function(url, status) {
    // NOTE: Do not use `res.redirect` from Express, because it can't decide
    //       what it wants.
    //
    //       Express 2.x: res.redirect(url, status)
    //       Express 3.x: res.redirect(status, url) -OR- res.redirect(url, status)
    //         - as of 3.14.0, deprecated warnings are issued if res.redirect(url, status)
    //           is used
    //       Express 4.x: res.redirect(status, url)
    //         - all versions (as of 4.8.7) continue to accept res.redirect(url, status)
    //           but issue deprecated versions

    res.statusCode = status || 302;       
    res.setHeader('Location', url);      <<<---- fail here
    res.setHeader('Content-Length', '0');
    res.end();
  };
```

**Comment by dyerti** [comment] 2015-06-18 00:30
Are you running my branch: https://github.com/dyerti/lets-chat/tree/gitlab-sso or the upstream develop?

My changes haven't been merged into develop as of yet.

**Comment by ghost** [comment] 2015-06-18 02:45
Ah, no. I'm running it directly from upstream develop. Then pulling your
plugins in. My changes are purely cosmetic.

From the look of it, your commits are exactly what I'm looking for. Do you
think this will get merged soon upstream?

I'll give your fork a shot tonight in my dev environment to test it out.

Thanks for your time and effort.

**Comment by ghost** [comment] 2015-06-18 05:31
OK new trace.  This is on a different VM in the cloud.
- cloned your branch down
- edited my settings.yaml for my ports
- npm installed without issue
- cloned google sso gh
- npm installed without issue
- edited settings again with my google api creds
- npm start, no problem

login as google user, get a whoops, server error.  But the cool thing is the gravatar works which is a nifty feature. 

output of trace below:

TypeError: Object function (err, user) {
                    if (err) {
                        return callback(err);
                    }
                    return callback(null, user);
                } has no method 'setHeader'
    at Strategy.strategy.redirect (/home/devvelochat/dyerti-sso-lets-chat/node_modules/passport/lib/middleware/authenticate.js:303:13)
    at Strategy.OAuth2Strategy.authenticate (/home/devvelochat/dyerti-sso-lets-chat/node_modules/lets-chat-google/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:227:10)
    at attempt (/home/devvelochat/dyerti-sso-lets-chat/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/home/devvelochat/dyerti-sso-lets-chat/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Google.authenticate (/home/devvelochat/dyerti-sso-lets-chat/node_modules/lets-chat-google/lib/auth.js:31:40)
    at /home/devvelochat/dyerti-sso-lets-chat/app/auth/index.js:209:26
    at fn (/home/devvelochat/dyerti-sso-lets-chat/node_modules/async/lib/async.js:716:34)
    at /home/devvelochat/dyerti-sso-lets-chat/node_modules/async/lib/async.js:1169:16
    at /home/devvelochat/dyerti-sso-lets-chat/node_modules/async/lib/async.js:661:43
    at Object.async.waterfall (/home/devvelochat/dyerti-sso-lets-chat/node_modules/async/lib/async.js:665:44)
    at /home/devvelochat/dyerti-sso-lets-chat/app/auth/index.js:218:15
    at checkIfAccountLocked (/home/devvelochat/dyerti-sso-lets-chat/app/auth/index.js:108:5)
    at Object.authenticate (/home/devvelochat/dyerti-sso-lets-chat/app/auth/index.js:186:5)
    at Object.app.io.route.login [as account:login](/home/devvelochat/dyerti-sso-lets-chat/app/controllers/account.js:273:18)
    at Server.io.route (/home/devvelochat/dyerti-sso-lets-chat/node_modules/express.oi/lib/index.js:55:25)
    at EventEmitter.<anonymous> (/home/devvelochat/dyerti-sso-lets-chat/node_modules/express.oi/lib/index.js:96:22)

**Comment by dyerti** [comment] 2015-06-22 18:46
Can you post your settings with your secrets removed?

I'll try to reproduce.

**Comment by ghost** [comment] 2015-06-23 15:10
Sorry for the late reply.

'
#

# Let's Chat Settings

#

# See defaults.yml for all available options

#

env: production # development / production

http:
  enable: true
  host: '0.0.0.0'
  port: 5000

https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem

xmpp:
  enable: false
  port: 5222
  domain: example.com

database:
  uri: mongodb://localhost/devletschat

secrets:
  cookie: secretsauce

files:
  enable: false
  provider: local
  maxFileSize: 100000000
  restrictTypes: true
  allowedTypes:
    - 'image/jpeg'
    - 'image/png'
    - 'image/gif'
  local:
    dir: uploads

auth:
  throttling:
    enable: true
    threshold: 3
  providers: [google]
  google:
    clientID: 'clientid.apps.googleusercontent.com'
    clientSecret: 'secret'
    callbackURL: 'https://moose.velochat.co/account/google/callback'
    scope: 'openid email profile'

private:
  enable: true
  roster: online # online / all
  expire: 360 # false or number of minutes

noRobots: true # Serve robots.txt with disallow

rooms:
  private: true

i18n:
  locale: en

'

**Comment by dyerti** [comment] 2015-06-24 23:41
Hmmm based on the line numbers from that trace it looks like you aren't using the branch.

My typical start from scratch setup:

```
git clone https://github.com/dyerti/lets-chat.git
git clone https://github.com/dyerti/lets-chat-google.git

cd lets-chat
git checkout gitlab-sso
npm install
npm install ../lets-chat-google

<edit settings.yml>

npm start
```

I can't reproduce with a fresh checkout.

**Comment by ghost** [comment] 2015-06-25 18:26
That works! Woot!

I didn't check out the right branch.

Great work BTW!

Thanks

## 

No trees were killed to send this message, but a large number of electrons
were terribly inconvenienced.

**Comment by dyerti** [comment] 2015-06-26 01:01
Great. Let me know if you run into anymore issues. I'm probably going to change how user ids are generated in the next week to minimize collisions between multiple SSO providers. The change will break existing user accounts, but I'll try to provide a migration.

**Closed as completed by dyerti** 2015-06-26 01:01 UTC
